region: "ru-01"
datacenter: "ru-01-la"
namespace: "production"
count: 1

env: "production"
app_region: "ru"
logger_level: ""

ticker_ssl_checker: "1h"
ticker_easylist_checker: "5m"

max_per_host: 1

balancers_ru:
  - 62.76.25.27
  - 62.76.25.28

balancers_sg:
  - 172.241.51.4
  - 172.241.51.14

cpu_limit: 500
memory_limit: 500
